services:
  backend:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lansub-backend
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    mem_limit: 2g

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lansub-frontend
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://98.70.44.251:9000/api
      - TZ=Asia/Kolkata
      - NODE_OPTIONS=--max-old-space-size=4096
    mem_limit: 4g
    memswap_limit: 4g
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
